# backend/storage/storage_driver.py
"""
Abstract StorageDriver interface + factory.

Other modules should import get_storage_driver() to get the concrete driver.
"""

from typing import Protocol, List, Dict, Any, Optional, Iterable


class StorageDriver(Protocol):
    async def create_pool_record(self, name: str, pool_type: Optional[str] = None, meta: Optional[Dict] = None) -> Any: ...
    async def list_pools_db(self) -> List[Dict[str, Any]]: ...
    async def get_pool_by_name(self, name: str) -> Optional[Any]: ...
    async def update_pool_status(self, name: str, status: str): ...
    async def delete_pool(self, name: str): ...

    async def add_vdev(self, pool_id: int, vdev_type: str, role: Optional[str] = None, meta: Optional[Dict] = None) -> Any: ...
    async def add_vdev_disk(self, vdev_id: int, disk_name: str) -> Any: ...

    async def upsert_disk(self, disk_obj: Dict[str, Any]) -> Any: ...
    async def bulk_upsert_disks(self, disks: Iterable[Dict[str, Any]]) -> Any: ...
    async def list_disks_db(self) -> List[Dict[str, Any]]: ...

    async def create_dataset_record(self, pool: str, name: str, mountpoint: Optional[str] = None, options: Optional[Dict] = None) -> Any: ...
    async def list_datasets_db(self, pool: Optional[str] = None) -> List[Dict[str, Any]]: ...

    async def add_share_record(self, name: str, path: str, protocol: str, options: Optional[Dict] = None) -> Any: ...
    async def list_shares_db(self) -> List[Dict[str, Any]]: ...

    async def add_acl_record(self, path: str, user: str, permissions: str) -> Any: ...
    async def list_acls_db(self, path: Optional[str] = None) -> List[Dict[str, Any]]: ...

    async def push_alert(self, level: str, source: str, message: str) -> Any: ...
    async def add_smart_history(self, disk_name: str, raw: Dict[str, Any], status: Optional[str] = None, temp_c: Optional[float] = None) -> Any: ...


# Factory helper to avoid circular imports
def get_storage_driver():
    # Lazy import so we don't force DB driver during tests
    from backend.drivers.storage_driver_mysql import StorageDriverMySQL
    return StorageDriverMySQL()
