# backend/alembic/versions/0001_initial.py
"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2025-11-xx xx:xx:xx.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pools',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False, server_default='UNKNOWN'),
        sa.Column('type', sa.String(length=32), nullable=True),
        sa.Column('size', sa.String(length=64), nullable=True),
        sa.Column('used', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.UniqueConstraint('name', name=op.f('uq_pools_name'))
    )
    op.create_index(op.f('ix_pools_name'), 'pools', ['name'], unique=False)

    op.create_table(
        'vdevs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('pool_id', sa.Integer(), nullable=False),
        sa.Column('vdev_type', sa.String(length=32), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    )
    op.create_index(op.f('ix_vdevs_pool_id'), 'vdevs', ['pool_id'], unique=False)

    op.create_table(
        'vdev_disks',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('vdev_id', sa.Integer(), nullable=False),
        sa.Column('disk_name', sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(['vdev_id'], ['vdevs.id'], ondelete='CASCADE'),
    )
    op.create_index(op.f('ix_vdev_disks_vdev_id'), 'vdev_disks', ['vdev_id'], unique=False)

    op.create_table(
        'disks',
        sa.Column('name', sa.String(length=128), primary_key=True),
        sa.Column('devpath', sa.String(length=256), nullable=False),
        sa.Column('size_gb', sa.Float(), nullable=True),
        sa.Column('model', sa.String(length=256), nullable=True),
        sa.Column('vendor', sa.String(length=128), nullable=True),
        sa.Column('rotational', sa.Boolean(), server_default=sa.text('1'), nullable=True),
        sa.Column('serial', sa.String(length=128), nullable=True),
        sa.Column('smart_status', sa.String(length=32), server_default='UNKNOWN', nullable=True),
        sa.Column('temp_c', sa.Float(), nullable=True),
        sa.Column('last_seen', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index(op.f('ix_disks_model'), 'disks', ['model'], unique=False)
    op.create_index(op.f('ix_disks_vendor'), 'disks', ['vendor'], unique=False)

    op.create_table(
        'datasets',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('pool', sa.String(length=128), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('mountpoint', sa.String(length=512), nullable=True),
        sa.Column('compression', sa.String(length=64), nullable=True),
        sa.Column('quota', sa.String(length=64), nullable=True),
        sa.Column('used', sa.String(length=64), nullable=True),
        sa.Column('options', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['pool'], ['pools.name'], ondelete='CASCADE'),
        sa.UniqueConstraint('pool', 'name', name=op.f('uq_dataset_pool_name'))
    )
    op.create_index(op.f('ix_datasets_pool'), 'datasets', ['pool'], unique=False)

    op.create_table(
        'snapshots',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('dataset_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('used', sa.String(length=64), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    )
    op.create_index(op.f('ix_snapshots_dataset_id'), 'snapshots', ['dataset_id'], unique=False)

    op.create_table(
        'shares',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('path', sa.String(length=512), nullable=False),
        sa.Column('protocol', sa.String(length=32), nullable=False),
        sa.Column('options', sa.JSON(), nullable=True),
    )
    op.create_index(op.f('ix_shares_protocol'), 'shares', ['protocol'], unique=False)

    op.create_table(
        'acl',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('path', sa.String(length=512), nullable=False),
        sa.Column('user', sa.String(length=128), nullable=False),
        sa.Column('permissions', sa.String(length=64), nullable=False),
    )
    op.create_index(op.f('ix_acl_path_user'), 'acl', ['path', 'user'], unique=False)

    op.create_table(
        'smart_history',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('disk_name', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('temp_c', sa.Float(), nullable=True),
        sa.Column('raw', sa.JSON(), nullable=True),
        sa.Column('ts', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index(op.f('ix_smart_disk'), 'smart_history', ['disk_name'], unique=False)

    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('kind', sa.String(length=64), nullable=False),
        sa.Column('target', sa.String(length=256), nullable=True),
        sa.Column('status', sa.String(length=32), server_default='pending', nullable=True),
        sa.Column('progress', sa.Float(), server_default='0', nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
    )

    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('level', sa.String(length=16), nullable=False),
        sa.Column('source', sa.String(length=128), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('0'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_smart_disk'), table_name='smart_history')
    op.drop_table('smart_history')
    op.drop_index(op.f('ix_acl_path_user'), table_name='acl')
    op.drop_table('acl')
    op.drop_index(op.f('ix_shares_protocol'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_snapshots_dataset_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_datasets_pool'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_disks_vendor'), table_name='disks')
    op.drop_index(op.f('ix_disks_model'), table_name='disks')
    op.drop_table('disks')
    op.drop_index(op.f('ix_vdev_disks_vdev_id'), table_name='vdev_disks')
    op.drop_table('vdev_disks')
    op.drop_index(op.f('ix_vdevs_pool_id'), table_name='vdevs')
    op.drop_table('vdevs')
    op.drop_index(op.f('ix_pools_name'), table_name='pools')
    op.drop_table('pools')
    # ### end Alembic commands ###
