# backend/drivers/base.py
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

class StorageDriver(ABC):
    """Abstract Storage Driver - managers call only this interface."""

    # Disks / Inventory
    @abstractmethod
    def list_disks(self) -> List[Dict[str, Any]]: ...

    # Pools
    @abstractmethod
    def list_pools(self) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def create_pool(self, name: str, layout: Dict[str, Any], dry_run: bool=False) -> Dict[str, Any]: ...
    @abstractmethod
    def destroy_pool(self, name: str, force: bool=False) -> Dict[str, Any]: ...

    # Datasets
    @abstractmethod
    def list_datasets(self, pool: Optional[str]=None) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def create_dataset(self, pool: str, name: str, mountpoint: Optional[str]=None) -> Dict[str, Any]: ...
    @abstractmethod
    def destroy_dataset(self, pool: str, name: str, recursive: bool=False) -> Dict[str, Any]: ...

    # Snapshots
    @abstractmethod
    def list_snapshots(self, pool: Optional[str]=None) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def create_snapshot(self, dataset: str, snapshot_name: str) -> Dict[str, Any]: ...
    @abstractmethod
    def destroy_snapshot(self, snapshot: str) -> Dict[str, Any]: ...

    # Shares (SMB/NFS)
    @abstractmethod
    def list_shares(self) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def create_share(self, meta: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    def delete_share(self, name: str) -> Dict[str, Any]: ...

    # ACLs / Permissions
    @abstractmethod
    def list_acls(self, path: str) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def set_acl(self, path: str, acl: List[Dict[str, Any]]) -> Dict[str, Any]: ...
    @abstractmethod
    def remove_acl(self, path: str, username: str) -> Dict[str, Any]: ...

    # SMART
    @abstractmethod
    def smart_health(self, devpath: str) -> Dict[str, Any]: ...

    # Utilities
    @abstractmethod
    def ping(self) -> Dict[str, Any]: ...
