
CREATE DATABASE IF NOT EXISTS mynas;
USE mynas;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(64) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Pools
CREATE TABLE IF NOT EXISTS pools (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  type VARCHAR(32) DEFAULT 'zfs',
  properties JSON NULL,
  health VARCHAR(32) DEFAULT 'UNKNOWN',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Pool devices / vdevs
CREATE TABLE IF NOT EXISTS pool_devices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_id BIGINT UNSIGNED NOT NULL,
  devpath VARCHAR(255) NOT NULL,
  role VARCHAR(64) DEFAULT 'data',
  vdev_index INT DEFAULT 0,
  FOREIGN KEY (pool_id) REFERENCES pools(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Datasets
CREATE TABLE IF NOT EXISTS datasets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  mountpoint VARCHAR(512) NULL,
  properties JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pool_id) REFERENCES pools(id) ON DELETE CASCADE,
  UNIQUE KEY pool_name_unique (pool_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Disks
CREATE TABLE IF NOT EXISTS disks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128),
  devpath VARCHAR(255) UNIQUE,
  model VARCHAR(255),
  vendor VARCHAR(255),
  size_bytes BIGINT,
  rotational BOOLEAN DEFAULT TRUE,
  smart_status JSON NULL,
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SMART history
CREATE TABLE IF NOT EXISTS smart_history (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  disk_id BIGINT,
  raw JSON,
  status VARCHAR(32),
  temp_c INT NULL,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (disk_id) REFERENCES disks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Shares
CREATE TABLE IF NOT EXISTS shares (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  path VARCHAR(1024),
  protocol VARCHAR(32),
  properties JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ACLs
CREATE TABLE IF NOT EXISTS acl (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(1024),
  username VARCHAR(255),
  permissions VARCHAR(64),
  is_group BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- System settings (key/value)
CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  key_name VARCHAR(255) NOT NULL UNIQUE,
  value_json JSON,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tasks / Audit log
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(64),
  level VARCHAR(16),
  message TEXT,
  meta JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NETWORK
CREATE TABLE IF NOT EXISTS network_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_name VARCHAR(64),
    value_json TEXT
);

